### ISSUE TITLE
 init][ 328]: AX_ENGINE_CreateHandle [E][Init][ 124]: init axmodel(tinyllama-int8/tinyllama_l1.axmodel) failed

### ISSUE THREAD

**Issue by 17656178609** [AXERA-TECH/ax-llm#4]
Running it once or twice and then running it again would cause such errors, requiring a restart of the board each time it was encountered.

**Comment by BUG1989** [comment]
- if you used AX650N, please check it bsp version is >= v1.45.0_P38
- using the llm build guide to get the new axmodel of TinyLlama1.1
